// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavPTVgq0X22NvIBUX5a-9pcJgHkmiwg8',
    appId: '1:563427434233:web:6f9ddab1b4e1c42ca9cc28',
    messagingSenderId: '563427434233',
    projectId: 'notilo-data',
    authDomain: 'notilo-data.firebaseapp.com',
    storageBucket: 'notilo-data.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sdjwF7KUjYCyRtQLIjcmJsxBJWVCBq4',
    appId: '1:563427434233:android:bb4a39144873f199a9cc28',
    messagingSenderId: '563427434233',
    projectId: 'notilo-data',
    storageBucket: 'notilo-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaWmEkNaNkpFumqbpAvQDJ3CdDRIB9UGY',
    appId: '1:563427434233:ios:a33392f2e9187e2fa9cc28',
    messagingSenderId: '563427434233',
    projectId: 'notilo-data',
    storageBucket: 'notilo-data.firebasestorage.app',
    iosBundleId: 'com.example.notilo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaWmEkNaNkpFumqbpAvQDJ3CdDRIB9UGY',
    appId: '1:563427434233:ios:a33392f2e9187e2fa9cc28',
    messagingSenderId: '563427434233',
    projectId: 'notilo-data',
    storageBucket: 'notilo-data.firebasestorage.app',
    iosBundleId: 'com.example.notilo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAavPTVgq0X22NvIBUX5a-9pcJgHkmiwg8',
    appId: '1:563427434233:web:6a6eb46d2fc719ffa9cc28',
    messagingSenderId: '563427434233',
    projectId: 'notilo-data',
    authDomain: 'notilo-data.firebaseapp.com',
    storageBucket: 'notilo-data.firebasestorage.app',
  );
}
